import { AllParts } from "./AllParts";
import { CardFaces } from "./CardFaces";
import { ImageUris } from "./ImageUris";
import { Legalities } from "./Legalities";
import { Preview } from "./Preview";
import { Prices } from "./Prices";
import { RelatedUris } from "./RelatedUris";

export class Card {
  public _id: string;
  public all_parts: AllParts[];
  public arena_id: number;
  public artist: string;
  public artist_ids: string[];
  public booster: boolean;
  public border_color: string;
  public card_back_id: string;
  public card_market_id: number;
  public card_faces: CardFaces[];
  public cmc: number;
  public collector_number: string;
  public color_identity: string[];
  public colors: string[];
  public digital: boolean;
  public edhrec_rank: number;
  public finishes: string[];
  public flavor_text: string;
  public foil: boolean;
  public frame: string;
  public full_art: boolean;
  public games: string[];
  public highres_image: boolean;
  public id: string;
  public illustration_id: string;
  public image_status: string;
  public image_uris: ImageUris;
  public keywords: string[];
  public lang: string;
  public layout: string;
  public legalities: Legalities;
  public life_modifier: string;
  public loyalty: string;
  public mana_cost: string;
  public mtgo_foil_id: number;
  public mtgo_id: number;
  public multiverse_ids: number[];
  public name: string;
  public nonfoil: boolean;
  public object: string;
  public oracle_id: string;
  public oracle_text: string;
  public oversized: boolean;
  public preview: Preview
  public prices: Prices;
  public power: string;
  public prints_search_uri: string;
  public promo: boolean;
  public promo_types: string[];
  public rarity: string;
  public related_uris: RelatedUris;
  public released_at: string;
  public reprint: boolean;
  public reserved: boolean;
  public rulings_uri: string;
  public scryfall_set_uri: string;
  public scryfall_uri: string;
  public set: string;
  public set_id: string;
  public set_name: string;
  public set_search_uri: string;
  public set_type: string;
  public set_uri: string;
  public story_spotlight: boolean;
  public tcgplayer_id: number;
  public textless: boolean;
  public toughness: string;
  public type_line: string;
  public uri: string;
  public variation: boolean;
  public variation_of: string;
  public watermark: string;
}
